CUDA_VISIBLE_DEVICES=0 python main.py \
    --lr 0.0009 \
    --dropout 0.2 \
    --batch_size 256 \
    --epochs 500 \
    --max_traj_len 3 \
    --max_traj_len_test 3 \
    --M 2 \
    --aug_range 0 \
    --step_size 40 \
    --lr_decay 0.65 \
    --model_name 'crosstask' \
    --dataset 'crosstask' \
    --num_action 133 \
    --num_tasks 18 \
    --img_input_dim 1536 \
    --text_input_dim 768 \
    --embed_dim 128 \
    --train_json '../../dataset/CrossTask/train_list_3_133.json' \
    --valid_json '../../dataset/CrossTask/test_list_3_133.json' \
    --saved_path 'checkpoints' \
    --seed 7