CUDA_VISIBLE_DEVICES=0 python main.py \
    --lr 0.0009 \
    --dropout 0.2 \
    --batch_size 256 \
    --epochs 500 \
    --max_traj_len 3 \
    --max_traj_len_test 3 \
    --M 2 \
    --aug_range 0 \
    --step_size 40 \
    --lr_decay 0.65 \
    --model_name 'coin' \
    --dataset 'coin' \
    --num_action 778 \
    --num_tasks 180 \
    --img_input_dim 1536 \
    --text_input_dim 768 \
    --embed_dim 128 \
    --train_json 'dataset/COIN/coin_train_70_3.json' \
    --valid_json 'dataset/COIN/coin_test_30_3.json' \
    --saved_path 'checkpoints' \
    --seed 7